# Generated by Django 4.2.3 on 2023-07-31 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
